image: archlinux
packages:
  - rust
  - cargo-audit
sources:
  - https://git.sr.ht/~danprobst/kinsaga
tasks:
  - fmt: |
      cd kinsaga
      cargo fmt --check
  - clippy: |
      cd kinsaga
      cargo clippy --all-targets -- -D warnings
  - test: |
      cd kinsaga
      cargo test
  - audit: |
      cd kinsaga
      cargo audit
